import type { Component } from 'vue'
import {
  ALargeSmall,
  AudioLines,
  ChartNoAxesColumnIncreasing,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  CircleQuestionMark,
  DiscAlbum,
  Download,
  Eraser,
  FileMusic,
  FolderOpen,
  Gauge,
  HardDrive,
  Headphones,
  Heart,
  HeartPlus,
  Info,
  ListOrdered,
  ListPlus,
  ListVideo,
  Lock,
  LockOpen,
  MessageSquareText,
  Minimize2,
  Minus,
  MonitorOff,
  MonitorUp,
  Music,
  Palette,
  Pause,
  Pin,
  PinOff,
  Play,
  Plus,
  RefreshCw,
  Repeat,
  Repeat1,
  Search,
  Settings,
  Share2,
  Shuffle,
  SkipBack,
  SkipForward,
  SlidersHorizontal,
  Smartphone,
  Sun,
  SunDim,
  TextCursorInput,
  ThumbsUp,
  Trash2,
  Undo2,
  Vibrate,
  VibrateOff,
  Volume,
  Volume1,
  Volume2,
  VolumeOff,
  VolumeX,
  X,
} from '@lucide/vue'

type IconComponent = Component

const iconAliases: Record<string, IconComponent> = {
  'add-2': HeartPlus,
  addTo: ListPlus,
  album: DiscAlbum,
  'angle-right-solid': ChevronRight,
  'audio-wave': AudioLines,
  back: Undo2,
  'check-indeterminate': Minus,
  'check-true': Check,
  close: X,
  comment: MessageSquareText,
  delete: Trash2,
  'desktop-lyric-off': MonitorOff,
  'desktop-lyric-on': MonitorUp,
  down: ChevronDown,
  download: Download,
  'download-2': Download,
  eraser: Eraser,
  first: ChevronsLeft,
  'font-decrease': ALargeSmall,
  'font-increase': ALargeSmall,
  'fullscreen-exit': Minimize2,
  headphones: Headphones,
  'help-circle-outline': CircleQuestionMark,
  'information-slab-circle-outline': Info,
  last: ChevronsRight,
  leaderboard: ChartNoAxesColumnIncreasing,
  left: ChevronLeft,
  'list-add': ListPlus,
  'list-loop': Repeat,
  'list-order': ListOrdered,
  'list-random': Shuffle,
  lock: Lock,
  logo: Music,
  love: Heart,
  music: Music,
  musicFile: FileMusic,
  nextMusic: SkipForward,
  'opactiy-decrease': SunDim,
  'opactiy-increase': Sun,
  pause: Pause,
  phone: Smartphone,
  play: Play,
  'play-outline': Play,
  plex: Gauge,
  plus: Plus,
  prevMusic: SkipBack,
  refresh: RefreshCw,
  right: ChevronRight,
  search: Search,
  'search-2': Search,
  setting: Settings,
  share: Share2,
  single: ListVideo,
  'single-loop': Repeat1,
  sound: Volume2,
  sdCard: HardDrive,
  musicFolder: FolderOpen,
  testPlay: Headphones,
  text: TextCursorInput,
  theme: Palette,
  'thumbs-up': ThumbsUp,
  'top-off': PinOff,
  'top-on': Pin,
  'tune-variant': SlidersHorizontal,
  unlock: LockOpen,
  vibrate: Vibrate,
  'vibrate-off': VibrateOff,
  'volume-high-outline': Volume2,
  'volume-low-outline': Volume1,
  'volume-medium-outline': Volume,
  'volume-mute-outline': VolumeX,
  'volume-off-outline': VolumeOff,
  'window-close': X,
  'window-close-2': X,
  'window-hide': ChevronDown,
  'window-minimize': Minus,
  'window-minimize-2': Minus,
}

export const fallbackIcon = CircleQuestionMark

export const getIconComponent = (name: string): IconComponent => iconAliases[name] ?? fallbackIcon
